'use client';
import { useState } from 'react';
import { Calendar, Filter, Download, ChevronDown, FileDown, MoreHorizontal } from 'lucide-react';

import KpiCard            from '@/components/eai/widgets/KpiCard';
import DonutChart         from '@/components/eai/widgets/DonutChart';
import TrendChart         from '@/components/eai/widgets/TrendChart';
import DataTable          from '@/components/eai/widgets/DataTable';
import HorizontalBarList  from '@/components/eai/widgets/HorizontalBarList';
import RegionUtilizationMap from '@/components/eai/widgets/RegionUtilizationMap';
import ToggleListCard     from '@/components/eai/widgets/ToggleListCard';
import QuickActionsMenu from '@/components/eai/widgets/QuickActionsMenu';

import {
  KPIS, ASSET_DISTRIBUTION, ASSET_VALUE_TREND,
  UTILIZATION_BY_LOCATION, OPERATIONAL_PERF, SLA_COMPLIANCE_TREND,
  TOP_LOCATIONS_BY_VALUE, COST_OVERVIEW, COST_PER_KW,
  RECENT_REPORTS, REPORTS_BY_CATEGORY, SCHEDULED_REPORTS, INSIGHTS,
} from '@/data/eaiReportsMock';

// ─── Shared card styles ────────────────────────────────────────────────────────
const CARD = {
  background: '#FFFFFF',
  border: '1px solid #E2E8F0',
  borderRadius: 12, overflow: 'hidden',
  boxShadow: '0 1px 2px rgba(16, 24, 40, 0.04)',
};
const CARD_HDR = {
  display: 'flex', alignItems: 'center', justifyContent: 'space-between',
  padding: '10px 14px', borderBottom: '1px solid #E2E8F0',
};
const CARD_TITLE = { fontSize: 11, fontWeight: 700, color: '#1A1F36', letterSpacing: '-0.01em' };
const LINK_STYLE = { fontSize: 9, color: '#0077C8', textDecoration: 'none', fontWeight: 600, display: 'inline-flex', alignItems: 'center', gap: 3 };
const DROPDOWN_BTN = {
  display: 'flex', alignItems: 'center', gap: 3,
  fontSize: 9, color: '#6B7280',
  background: '#F8FAFC', border: '1px solid #E2E8F0',
  borderRadius: 6, padding: '3px 8px', cursor: 'pointer',
};
const GAP = 10;

// ─── Format pill ───────────────────────────────────────────────────────────────
const FORMAT_STYLE = {
  PDF:   { color: '#0077C8', bg: 'rgba(0,119,200,0.15)',   border: 'rgba(0,119,200,0.30)'   },
  Excel: { color: '#00A36C', bg: 'rgba(0,163,108,0.15)',   border: 'rgba(0,163,108,0.30)'   },
};

// ─── Operational Performance mini stat tile ────────────────────────────────────
function MiniStat({ label, value, unit = '', delta, up }) {
  return (
    <div style={{
      background: '#F8FAFC', border: '1px solid #E2E8F0',
      borderRadius: 10, padding: '9px 10px',
    }}>
      <p style={{ fontSize: 8, color: '#9CA3AF', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: 4 }}>{label}</p>
      <p style={{ fontSize: 20, fontWeight: 700, color: '#1A1F36', fontFamily: 'monospace', lineHeight: 1, marginBottom: 3 }}>
        {value}{unit && <span style={{ fontSize: 10, fontWeight: 500, color: '#6B7280', marginLeft: 2 }}>{unit}</span>}
      </p>
      <p style={{ fontSize: 9, fontWeight: 600, color: up ? '#00A36C' : '#DC2626' }}>{delta}</p>
    </div>
  );
}

// ─── Recent Reports table columns ─────────────────────────────────────────────
const REPORT_COLS = [
  { key: 'reportName',   label: 'Report Name' },
  { key: 'category',     label: 'Category',    width: 130,
    render: v => <span style={{ fontSize: 9, color: '#6B7280' }}>{v}</span> },
  { key: 'generatedOn',  label: 'Generated On', width: 148,
    render: v => <span style={{ fontSize: 9, color: '#6B7280' }}>{v}</span> },
  { key: 'generatedBy',  label: 'Generated By', width: 90,
    render: v => <span style={{ fontSize: 9, color: '#6B7280' }}>{v}</span> },
  { key: 'format',       label: 'Format',       width: 56, align: 'center',
    render: v => {
      const s = FORMAT_STYLE[v] ?? FORMAT_STYLE.PDF;
      return (
        <span style={{ fontSize: 8, fontWeight: 700, padding: '2px 6px', borderRadius: 5,
          color: s.color, background: s.bg, border: `1px solid ${s.border}` }}>
          {v}
        </span>
      );
    },
  },
  { key: '_act',         label: '',             width: 52, align: 'center',
    render: (_, row) => (
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 6 }}>
        <FileDown size={11} style={{ color: '#6B7280', cursor: 'pointer' }} />
        <MoreHorizontal size={11} style={{ color: '#6B7280', cursor: 'pointer' }} />
      </div>
    ),
  },
];

// ─── Tab definitions ──────────────────────────────────────────────────────────
const TABS = [
  { key: 'overview',         label: 'Overview'         },
  { key: 'dashboards',       label: 'Dashboards'       },
  { key: 'reports-library',  label: 'Reports Library'  },
  { key: 'data-explorer',    label: 'Data Explorer'    },
];

// ─── Page ──────────────────────────────────────────────────────────────────────
export default function ReportsAnalyticsPage() {
  const [activeSection, setActiveSection] = useState('overview');
  const [activeTab,     setActiveTab]     = useState('overview');

  return (
    <div style={{ display: 'flex', height: 'calc(100vh - 56px)', overflow: 'hidden' }}>
      <div style={{ flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden', minWidth: 0 }}>

        {/* ── Sub-header ─────────────────────────────────────────────────────── */}
        <div style={{
          padding: '12px 20px 0',
          borderBottom: '1px solid #E2E8F0',
          flexShrink: 0,
          background: '#F4F6F9',
        }}>
          {/* Title + controls row */}
          <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: 10 }}>
            <div>
              <h1 style={{ fontSize: 16, fontWeight: 800, color: '#1A1F36', letterSpacing: '-0.02em', lineHeight: 1.2 }}>
                Reports &amp; Analytics
              </h1>
              <p style={{ fontSize: 10, color: '#6B7280', marginTop: 2 }}>
                Gain actionable insights through powerful analytics and customizable reports
              </p>
            </div>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginTop: 2, flexShrink: 0 }}>
              {/* Date range */}
              <button style={{
                display: 'flex', alignItems: 'center', gap: 5,
                background: '#F8FAFC', border: '1px solid #E2E8F0',
                borderRadius: 8, padding: '5px 10px', cursor: 'pointer',
                color: '#6B7280', fontSize: 10,
              }}>
                <Calendar size={11} />
                May 1 – May 31, 2025
                <ChevronDown size={10} />
              </button>
              {/* Filters */}
              <button style={{
                display: 'flex', alignItems: 'center', gap: 5,
                background: '#F8FAFC', border: '1px solid #E2E8F0',
                borderRadius: 8, padding: '5px 10px', cursor: 'pointer',
                color: '#6B7280', fontSize: 10,
              }}>
                <Filter size={11} /> Filters
              </button>
              {/* Export split button */}
              <div style={{ display: 'flex', borderRadius: 8, overflow: 'hidden', border: '1px solid rgba(0,119,200,0.50)' }}>
                <button style={{
                  display: 'flex', alignItems: 'center', gap: 5,
                  background: 'linear-gradient(135deg, #0077C8 0%, #005EA6 100%)',
                  border: 'none', padding: '5px 12px', cursor: 'pointer',
                  color: '#fff', fontSize: 10, fontWeight: 600,
                }}>
                  <Download size={11} /> Export
                </button>
                <button style={{
                  background: '#005EA6', border: 'none',
                  borderLeft: '1px solid rgba(0,119,200,0.50)',
                  padding: '5px 7px', cursor: 'pointer', color: '#fff',
                }}>
                  <ChevronDown size={10} />
                </button>
              </div>
              <QuickActionsMenu items={[
                { iconKey: 'FilePlus',    label: 'Create Report'      },
                { iconKey: 'CalendarPlus',label: 'Schedule Report'    },
                { iconKey: 'Download',    label: 'Export Data'        },
                { iconKey: 'LayoutGrid',  label: 'Manage Dashboards'  },
              ]} />
            </div>
          </div>

          {/* Tab strip */}
          <div style={{ display: 'flex', gap: 0 }}>
            {TABS.map(tab => {
              const isActive = activeTab === tab.key;
              return (
                <button
                  key={tab.key}
                  onClick={() => setActiveTab(tab.key)}
                  style={{
                    padding: '7px 14px', border: 'none', background: 'transparent',
                    cursor: 'pointer', fontSize: 11, fontWeight: isActive ? 700 : 500,
                    color: isActive ? '#0077C8' : '#9CA3AF',
                    borderBottom: isActive ? '2px solid #0077C8' : '2px solid transparent',
                    marginBottom: -1, transition: 'all 0.12s',
                  }}
                  onMouseEnter={e => { if (!isActive) e.currentTarget.style.color = '#1A1F36'; }}
                  onMouseLeave={e => { if (!isActive) e.currentTarget.style.color = '#9CA3AF'; }}
                >
                  {tab.label}
                </button>
              );
            })}
          </div>
        </div>

        {/* ── Scrollable body ────────────────────────────────────────────────── */}
        <div style={{ flex: 1, overflowY: 'auto', padding: '14px 20px', display: 'flex', flexDirection: 'column', gap: GAP }}>

          {activeTab === 'overview' ? (
            <>
              {/* ── KPI row ───────────────────────────────────────────────────── */}
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(6, 1fr)', gap: GAP }}>
                {KPIS.map(k => <KpiCard key={k.label} {...k} />)}
              </div>

              {/* ── Row 1: Distribution | Trend | Map ────────────────────────── */}
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1.35fr 1.15fr', gap: GAP, alignItems: 'start' }}>

                {/* Asset Distribution by Type */}
                <div style={{ ...CARD, display: 'flex', flexDirection: 'column' }}>
                  <div style={CARD_HDR}><span style={CARD_TITLE}>Asset Distribution by Type</span></div>
                  <div style={{ padding: '12px 14px 8px' }}>
                    <DonutChart
                      data={ASSET_DISTRIBUTION}
                      centerLabel="21,342"
                      centerSublabel="Total Assets"
                      height={170}
                      innerRadius={52}
                      outerRadius={74}
                    />
                  </div>
                  <div style={{ padding: '0 14px 10px' }}>
                    <a href="#" style={LINK_STYLE}>View full report →</a>
                  </div>
                </div>

                {/* Asset Value Trend */}
                <div style={{ ...CARD, display: 'flex', flexDirection: 'column' }}>
                  <div style={CARD_HDR}>
                    <span style={CARD_TITLE}>Asset Value Trend (USD)</span>
                    <button style={DROPDOWN_BTN}>Last 6 Months <ChevronDown size={9} /></button>
                  </div>
                  <div style={{ padding: '12px 14px 8px' }}>
                    <div style={{ display: 'flex', alignItems: 'baseline', gap: 4, marginBottom: 8 }}>
                      <span style={{ fontSize: 9, color: '#9CA3AF' }}>USD</span>
                    </div>
                    <TrendChart
                      data={ASSET_VALUE_TREND}
                      color="#0077C8"
                      unit="B"
                      height={140}
                      dataKey="value"
                      xKey="week"
                    />
                  </div>
                  <div style={{ padding: '0 14px 10px' }}>
                    <a href="#" style={LINK_STYLE}>View full report →</a>
                  </div>
                </div>

                {/* Utilization by Location */}
                <div style={{ ...CARD, display: 'flex', flexDirection: 'column' }}>
                  <div style={CARD_HDR}>
                    <span style={CARD_TITLE}>Utilization by Location</span>
                    <button style={DROPDOWN_BTN}>Utilization Rate <ChevronDown size={9} /></button>
                  </div>
                  <div style={{ padding: 0, overflow: 'hidden' }}>
                    <RegionUtilizationMap regions={UTILIZATION_BY_LOCATION} height={220} />
                  </div>
                  <div style={{ padding: '8px 14px 10px' }}>
                    <a href="#" style={LINK_STYLE}>View full report →</a>
                  </div>
                </div>
              </div>

              {/* ── Row 2: [Ops + SLA] | Top Locations | [Cost + kW] ─────────── */}
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: GAP, alignItems: 'start' }}>

                {/* Left: Operational Performance + SLA Trend */}
                <div style={{ display: 'flex', flexDirection: 'column', gap: GAP }}>

                  {/* Operational Performance */}
                  <div style={CARD}>
                    <div style={CARD_HDR}><span style={CARD_TITLE}>Operational Performance</span></div>
                    <div style={{ padding: '10px 14px 12px', display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8 }}>
                      {OPERATIONAL_PERF.map(p => (
                        <MiniStat
                          key={p.label}
                          label={p.label}
                          value={p.value}
                          unit={p.unit ?? ''}
                          delta={p.delta}
                          up={p.up}
                        />
                      ))}
                    </div>
                  </div>

                  {/* SLA Compliance Trend */}
                  <div style={CARD}>
                    <div style={CARD_HDR}>
                      <span style={CARD_TITLE}>SLA Compliance Trend</span>
                      <button style={DROPDOWN_BTN}>Last 6 Months <ChevronDown size={9} /></button>
                    </div>
                    <div style={{ padding: '8px 14px 8px' }}>
                      {/* Y-axis labels on left */}
                      <TrendChart
                        data={SLA_COMPLIANCE_TREND}
                        color="#00A36C"
                        unit="%"
                        height={120}
                        dataKey="value"
                        xKey="week"
                        domain={[80, 100]}
                      />
                    </div>
                    <div style={{ padding: '0 14px 10px' }}>
                      <a href="#" style={LINK_STYLE}>View full report →</a>
                    </div>
                  </div>
                </div>

                {/* Middle: Top 5 Locations by Asset Value */}
                <div style={CARD}>
                  <div style={CARD_HDR}><span style={CARD_TITLE}>Top 5 Locations by Asset Value</span></div>
                  <div style={{ padding: '12px 14px 8px' }}>
                    <div style={{ display: 'flex', justifyContent: 'flex-end', marginBottom: 8 }}>
                      <span style={{ fontSize: 8, color: '#9CA3AF', textTransform: 'uppercase', letterSpacing: '0.06em' }}>Value (USD)</span>
                    </div>
                    <HorizontalBarList
                      items={TOP_LOCATIONS_BY_VALUE}
                      maxValue={412.3}
                      prefix="$"
                      unit="M"
                      labelWidth={78}
                    />
                    <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: 10, fontSize: 8, color: '#9CA3AF' }}>
                      {['$0', '$100M', '$200M', '$300M', '$400M', '$500M'].map(l => <span key={l}>{l}</span>)}
                    </div>
                  </div>
                  <div style={{ padding: '6px 14px 10px' }}>
                    <a href="#" style={LINK_STYLE}>View full report →</a>
                  </div>
                </div>

                {/* Right: Cost Overview + Cost/kW stacked */}
                <div style={{ display: 'flex', flexDirection: 'column', gap: GAP }}>

                  {/* Cost Overview */}
                  <div style={CARD}>
                    <div style={CARD_HDR}>
                      <span style={CARD_TITLE}>Cost Overview (USD)</span>
                    </div>
                    <div style={{ padding: '10px 14px 8px' }}>
                      {/* Total cost */}
                      <div style={{ display: 'flex', alignItems: 'flex-start', gap: 12 }}>
                        <div style={{ flex: 1, minWidth: 0 }}>
                          <p style={{ fontSize: 22, fontWeight: 700, color: '#1A1F36', fontFamily: 'monospace', lineHeight: 1 }}>
                            {COST_OVERVIEW.totalCostYtd}
                          </p>
                          <p style={{ fontSize: 9, color: '#DC2626', fontWeight: 600, marginTop: 3 }}>
                            ↑{COST_OVERVIEW.deltaPct} {COST_OVERVIEW.deltaLabel}
                          </p>
                          <div style={{ marginTop: 10, display: 'flex', flexDirection: 'column', gap: 4 }}>
                            {COST_OVERVIEW.categoryBreakdown.map(c => (
                              <div key={c.name} style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                                <div style={{ display: 'flex', alignItems: 'center', gap: 5, minWidth: 0 }}>
                                  <span style={{ width: 6, height: 6, borderRadius: '50%', background: c.color, display: 'inline-block', flexShrink: 0 }} />
                                  <span style={{ fontSize: 9, color: '#6B7280', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{c.name}</span>
                                </div>
                                <span style={{ fontSize: 9, fontWeight: 700, color: '#1A1F36', fontFamily: 'monospace', whiteSpace: 'nowrap', marginLeft: 6 }}>
                                  ${c.value}M
                                  <span style={{ color: '#9CA3AF', fontWeight: 400, marginLeft: 3 }}>({c.pct}%)</span>
                                </span>
                              </div>
                            ))}
                          </div>
                        </div>
                        {/* Donut (small, no legend) */}
                        <div style={{ flexShrink: 0, width: 90 }}>
                          <DonutChart
                            data={COST_OVERVIEW.categoryBreakdown}
                            height={90}
                            innerRadius={24}
                            outerRadius={40}
                            showLegend={false}
                          />
                        </div>
                      </div>
                    </div>
                    <div style={{ padding: '0 14px 10px' }}>
                      <a href="#" style={LINK_STYLE}>View full report →</a>
                    </div>
                  </div>

                  {/* Cost / kW Monthly */}
                  <div style={CARD}>
                    <div style={CARD_HDR}><span style={CARD_TITLE}>Cost / kW Monthly</span></div>
                    <div style={{ padding: '10px 14px 10px', display: 'flex', alignItems: 'flex-start', gap: 8 }}>
                      <div style={{ flex: 1 }}>
                        <p style={{ fontSize: 24, fontWeight: 700, color: '#1A1F36', fontFamily: 'monospace', lineHeight: 1 }}>
                          {COST_PER_KW.value}
                        </p>
                        <p style={{ fontSize: 9, fontWeight: 600, color: '#00A36C', marginTop: 3 }}>{COST_PER_KW.delta}</p>
                      </div>
                      <div style={{ flex: 1 }}>
                        <TrendChart
                          data={COST_PER_KW.trend}
                          color="#0077C8"
                          height={56}
                          dataKey="value"
                          xKey="week"
                        />
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              {/* ── Row 3: Recent Reports | Reports by Category | Scheduled + Insights ── */}
              <div style={{ display: 'grid', gridTemplateColumns: '1.5fr 0.9fr 1fr', gap: GAP, alignItems: 'start', paddingBottom: 20 }}>

                {/* Recent Reports DataTable */}
                <DataTable
                  title="Recent Reports"
                  viewAllHref="#"
                  viewAllLabel="View all reports →"
                  columns={REPORT_COLS}
                  data={RECENT_REPORTS}
                  keyField="id"
                  compact
                />

                {/* Reports by Category */}
                <div style={{ ...CARD, display: 'flex', flexDirection: 'column' }}>
                  <div style={CARD_HDR}><span style={CARD_TITLE}>Reports by Category</span></div>
                  <div style={{ padding: '12px 14px 8px' }}>
                    <DonutChart
                      data={REPORTS_BY_CATEGORY}
                      centerLabel="156"
                      centerSublabel="Total Reports"
                      height={160}
                      innerRadius={48}
                      outerRadius={68}
                    />
                  </div>
                  <div style={{ padding: '0 14px 10px' }}>
                    <a href="#" style={LINK_STYLE}>View all reports →</a>
                  </div>
                </div>

                {/* Right: Scheduled Reports + Insights */}
                <div style={{ display: 'flex', flexDirection: 'column', gap: GAP }}>

                  <ToggleListCard
                    title="Scheduled Reports"
                    items={SCHEDULED_REPORTS}
                    viewAllHref="#"
                  />

                  {/* Insights */}
                  <div style={CARD}>
                    <div style={CARD_HDR}>
                      <span style={CARD_TITLE}>Insights</span>
                      <a href="#" style={{ fontSize: 9, color: '#0077C8', textDecoration: 'none', fontWeight: 600 }}>
                        View all insights →
                      </a>
                    </div>
                    <div style={{ padding: '8px 14px 10px', display: 'flex', flexDirection: 'column', gap: 8 }}>
                      {INSIGHTS.map((ins, i) => (
                        <div key={i} style={{
                          display: 'flex', alignItems: 'flex-start', gap: 8,
                          paddingBottom: i < INSIGHTS.length - 1 ? 8 : 0,
                          borderBottom: i < INSIGHTS.length - 1 ? '1px solid #E2E8F0' : 'none',
                        }}>
                          <span style={{
                            width: 7, height: 7, borderRadius: '50%',
                            background: ins.color,
                            boxShadow: `0 0 5px ${ins.color}70`,
                            display: 'inline-block', flexShrink: 0, marginTop: 3,
                          }} />
                          <div style={{ flex: 1, minWidth: 0 }}>
                            <p style={{ fontSize: 10, color: '#6B7280', lineHeight: 1.45 }}>{ins.message}</p>
                            <a href={ins.href} style={{ fontSize: 9, color: '#0077C8', textDecoration: 'none', fontWeight: 600, marginTop: 2, display: 'inline-block' }}>
                              {ins.linkLabel} →
                            </a>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>

                </div>
              </div>
            </>
          ) : (
            /* ── Placeholder tabs ──────────────────────────────────────────── */
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: 300, flexDirection: 'column', gap: 10 }}>
              <p style={{ fontSize: 16, fontWeight: 700, color: '#9CA3AF' }}>
                {TABS.find(t => t.key === activeTab)?.label}
              </p>
              <p style={{ fontSize: 12, color: '#9CA3AF' }}>Coming soon</p>
            </div>
          )}

        </div>
      </div>
    </div>
  );
}
